// src/components/Header.jsx
import React from "react";
import instagram from "../assets/icons/instagram.svg";
import facebook from "../assets/icons/facebook.svg";
import twitter from "../assets/icons/twitter.svg";
import github from "../assets/icons/github.svg";
import "../assets/styles/Header.css";

export default function Header() {
  return (
    <header>
      <p id="title">Lucar Affaled</p>
      <div className="social-links">
        <a href="#">
          <img
            src={instagram}
            alt="instagram link icon"
            className="social-icon"
          />
        </a>
        <a href="#">
          <img
            src={facebook}
            alt="Facebook link icon"
            className="social-icon"
          />
        </a>
        <a href="#">
          <img src={twitter} alt="Twitter link icon" className="social-icon" />
        </a>
        <a href="#">
          <img src={github} alt="Github link icon" className="social-icon" />
        </a>
      </div>
    </header>
  );
}

// src/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: [
    './header.component.scss',
    '../../styles.functions.scss',
    '../../styles.variables.scss',
  ],
})
export class HeaderComponent {}

<div class="header">
  <a [routerLink]="['']"><h1>Affaled</h1></a>
  <div class="header__social-icon">
    <a href="#"
      ><img src="../../assets/svgs/instagram-svgrepo.svg" alt="instagram"
    /></a>
    <a href="#"
      ><img src="../../assets/svgs/facebook-svgrepo.svg" alt="facebook"
    /></a>
    <a href="#"
      ><img src="../../assets/svgs/twitter-svgrepo.svg" alt="twitter"
    /></a>
  </div>
</div>
